spring:
  application:
    name: OverSea
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/over_sea_db
    username: root
    password: caixiang4,
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 100